version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - chmod +x scripts/pipeline-common/install-terraform.sh
      - scripts/pipeline-common/install-terraform.sh

  build:
    commands:
      - chmod +x terraform/config/pipeline-provisioner/scripts/provision-pipelines.sh
      - terraform/config/pipeline-provisioner/scripts/provision-pipelines.sh

artifacts:
  files:
    - '**/*'
