version: 0.2

env:
  variables:
    DYNAMODB_TABLE_NAME: "AccountPool"
    AWS_REGION: "us-east-2"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y jq
      - chmod +x terraform/sandbox/scripts/setup_env.sh
      - ./terraform/sandbox/scripts/setup_env.sh
      - pip install -r terraform/sandbox/scripts/requirements.txt

  build:
    commands:
      # --- Management Cluster ---
      - echo "=== Starting Management Cluster Deployment ==="

      - echo "Leasing Management Account..."
      - export MGMT_LEASE_OUTPUT=$(python3 terraform/sandbox/scripts/lease_account.py)
      - export MGMT_ACCOUNT_ID=$(echo $MGMT_LEASE_OUTPUT | jq -r '.account_id')
      # Persist Account ID for post_build cleanup
      - echo "$MGMT_ACCOUNT_ID" > /tmp/mgmt_account_id

      - export AWS_ACCESS_KEY_ID_MGMT=$(echo $MGMT_LEASE_OUTPUT | jq -r '.credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY_MGMT=$(echo $MGMT_LEASE_OUTPUT | jq -r '.credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN_MGMT=$(echo $MGMT_LEASE_OUTPUT | jq -r '.credentials.SessionToken // empty')

      - echo "Deploying Management Cluster in Account $MGMT_ACCOUNT_ID..."
      - cd terraform/config/management-cluster
      - cp terraform.tfvars.example terraform.tfvars
      # Run Terraform with leased credentials
      - |
        (
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_MGMT
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_MGMT
          export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN_MGMT
          terraform init
          terraform apply -auto-approve
        )
      - cd ../../../

      - echo "Bootstrapping ArgoCD for Management Cluster..."
      # Run bootstrap script with leased credentials
      - |
        (
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_MGMT
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_MGMT
          export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN_MGMT
          ./scripts/bootstrap-argocd.sh management
        )

      # --- Regional Cluster ---
      - echo "=== Starting Regional Cluster Deployment ==="

      - echo "Leasing Regional Account..."
      - export REG_LEASE_OUTPUT=$(python3 terraform/sandbox/scripts/lease_account.py)
      - export REG_ACCOUNT_ID=$(echo $REG_LEASE_OUTPUT | jq -r '.account_id')
      # Persist Account ID for post_build cleanup
      - echo "$REG_ACCOUNT_ID" > /tmp/reg_account_id

      - export AWS_ACCESS_KEY_ID_REG=$(echo $REG_LEASE_OUTPUT | jq -r '.credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY_REG=$(echo $REG_LEASE_OUTPUT | jq -r '.credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN_REG=$(echo $REG_LEASE_OUTPUT | jq -r '.credentials.SessionToken // empty')

      - echo "Deploying Regional Cluster in Account $REG_ACCOUNT_ID..."
      - cd terraform/config/regional-cluster
      - cp terraform.tfvars.example terraform.tfvars
      # Run Terraform with leased credentials
      - |
        (
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_REG
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_REG
          export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN_REG
          terraform init
          terraform apply -auto-approve
        )
      - cd ../../../

      - echo "Bootstrapping ArgoCD for Regional Cluster..."
      # Run bootstrap script with leased credentials
      - |
        (
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_REG
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_REG
          export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN_REG
          ./scripts/bootstrap-argocd.sh regional
        )

  post_build:
    commands:
      - echo "=== Cleaning up ==="

      - |
        if [ -f /tmp/mgmt_account_id ]; then
          MGMT_ACCOUNT_ID=$(cat /tmp/mgmt_account_id)
          echo "Releasing Management Account $MGMT_ACCOUNT_ID..."
          python3 terraform/sandbox/scripts/release_account.py $MGMT_ACCOUNT_ID || echo "Error: Failed to release Management Account $MGMT_ACCOUNT_ID"
        else
          echo "No Management Account to release."
        fi

      - |
        if [ -f /tmp/reg_account_id ]; then
          REG_ACCOUNT_ID=$(cat /tmp/reg_account_id)
          echo "Releasing Regional Account $REG_ACCOUNT_ID..."
          python3 terraform/sandbox/scripts/release_account.py $REG_ACCOUNT_ID || echo "Error: Failed to release Regional Account $REG_ACCOUNT_ID"
        else
          echo "No Regional Account to release."
        fi
