#!/usr/bin/env bash
# Provision or destroy Regional Cluster infrastructure.
# Called from: terraform/config/pipeline-regional-cluster/buildspec-provision-infra.yml
set -euo pipefail

echo "=========================================="
echo "Provisioning Regional Cluster Infrastructure"
echo "Build #${CODEBUILD_BUILD_NUMBER:-?} | ${CODEBUILD_BUILD_ID:-unknown}"
echo "=========================================="

# Pre-flight setup (validates env vars, inits account helpers)
source scripts/pipeline-common/setup-apply-preflight.sh

# Assume target account role for both state and resource operations
use_mc_account
echo ""

echo "Deploying to account: ${TARGET_ACCOUNT_ID}"
echo "  Region: ${TARGET_REGION}"
echo "  Regional ID: ${REGIONAL_ID}"
echo ""

# Configure Terraform backend (state in target account)
export TF_STATE_BUCKET="terraform-state-${TARGET_ACCOUNT_ID}"
export TF_STATE_KEY="regional-cluster/${REGIONAL_ID}.tfstate"
export TF_STATE_REGION="${TARGET_REGION}"

echo "Terraform backend:"
echo "  Bucket: $TF_STATE_BUCKET (target account: $TARGET_ACCOUNT_ID)"
echo "  Key: $TF_STATE_KEY"
echo "  Region: $TF_STATE_REGION"
echo ""

# Set Terraform variables
export TF_VAR_region="${TARGET_REGION}"
export TF_VAR_app_code="${APP_CODE}"
export TF_VAR_service_phase="${SERVICE_PHASE}"
export TF_VAR_cost_center="${COST_CENTER}"

# Set repository URL and branch with proper fallback handling for set -u
# Note: CODEBUILD_SOURCE_VERSION contains S3 artifact location, not git branch
# Use REPOSITORY_BRANCH (from CodeBuild env vars) or GITHUB_BRANCH instead
_REPO_BRANCH="${REPOSITORY_BRANCH:-${GITHUB_BRANCH:-main}}"
export TF_VAR_repository_url="${REPOSITORY_URL:-https://github.com/${GITHUB_REPOSITORY}.git}"
export TF_VAR_repository_branch="${_REPO_BRANCH}"

export TF_VAR_api_additional_allowed_accounts="${TARGET_ACCOUNT_ID}"

# Set container image for ECS tasks (bastion and bootstrap)
if [ -z "${PLATFORM_IMAGE:-}" ]; then
    echo "ERROR: PLATFORM_IMAGE is not set or empty; cannot set TF_VAR_container_image" >&2
    exit 1
fi
export TF_VAR_container_image="${PLATFORM_IMAGE}"

# Set enable_bastion variable (default to false if not set)
ENABLE_BASTION="${ENABLE_BASTION:-false}"
if [ "$ENABLE_BASTION" == "true" ] || [ "$ENABLE_BASTION" == "1" ]; then
    export TF_VAR_enable_bastion="true"
else
    export TF_VAR_enable_bastion="false"
fi

# Set DNS variables (optional — when ENVIRONMENT_DOMAIN is set, creates regional
# DNS zone and custom API domain)
if [ -n "${ENVIRONMENT_DOMAIN:-}" ]; then
    export TF_VAR_environment_domain="${ENVIRONMENT_DOMAIN}"
fi
if [ -n "${ENVIRONMENT_HOSTED_ZONE_ID:-}" ]; then
    export TF_VAR_environment_hosted_zone_id="${ENVIRONMENT_HOSTED_ZONE_ID}"
fi

echo "Terraform variables:"
echo "  Region: $TF_VAR_region"
echo "  App Code: $TF_VAR_app_code"
echo "  Service Phase: $TF_VAR_service_phase"
echo "  Cost Center: $TF_VAR_cost_center"
echo "  Repository URL: $TF_VAR_repository_url"
echo "  Repository Branch: $TF_VAR_repository_branch"
echo "  API Additional Allowed Accounts: $TF_VAR_api_additional_allowed_accounts"
echo "  Enable Bastion: $TF_VAR_enable_bastion"
echo "  Environment Domain: ${TF_VAR_environment_domain:-<not set>}"
echo "  Environment Hosted Zone ID: ${TF_VAR_environment_hosted_zone_id:-<not set>}"
echo ""

# Export required environment variables for Makefile target
# For regional clusters, verify generated terraform config exists before provisioning
export ENVIRONMENT="${ENVIRONMENT:-staging}"
RC_CONFIG_FILE="deploy/${ENVIRONMENT}/${TARGET_REGION}/terraform/regional.json"
if [ ! -f "$RC_CONFIG_FILE" ]; then
    echo "ERROR: Regional cluster config not found: $RC_CONFIG_FILE"
    echo "   This file should be generated by scripts/render.py"
    exit 1
fi


# Extract regional_id, environment, and sector from rendered config
export TF_VAR_regional_id=$(jq -r '.regional_id' "$RC_CONFIG_FILE")
export TF_VAR_environment=$(jq -r '.environment' "$RC_CONFIG_FILE")
export TF_VAR_sector=$(jq -r '.sector' "$RC_CONFIG_FILE")
echo "  Regional ID: $TF_VAR_regional_id"
echo "  Environment: $TF_VAR_environment"
echo "  Sector: $TF_VAR_sector"

# Read delete flag from config (GitOps-driven deletion)
DELETE_FLAG=$(jq -r '.delete // false' "$RC_CONFIG_FILE")
# Manual override: IS_DESTROY pipeline variable takes precedence
[ "${IS_DESTROY:-false}" == "true" ] && DELETE_FLAG="true"

echo ""
if [ "${DELETE_FLAG}" == "true" ]; then
    echo ">>> MODE: TEARDOWN <<<"
else
    echo ">>> MODE: PROVISION <<<"
fi
echo ""

if [ "${DELETE_FLAG}" == "true" ]; then
    make pipeline-destroy-regional
else
    make pipeline-provision-regional
fi
