{{- if gt (int (.Values.sigv4ProxyLogs.replicas | default 2)) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sigv4-proxy-logs
  namespace: vector
  labels:
    app.kubernetes.io/name: sigv4-proxy-logs
    app.kubernetes.io/component: logs-proxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sigv4-proxy-logs
{{- end }}
