{{- if .Values.global.cluster_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStore.secretName }}
  namespace: {{ include "thanos-operator.namespace" . }}
  labels:
    {{- include "thanos-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "thanos-operator.annotations" . | nindent 4 }}
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: {{ printf "%s-thanos-metrics" .Values.global.cluster_name | quote }}
      endpoint: {{ printf "s3.%s.amazonaws.com" .Values.global.aws_region | quote }}
      region: {{ .Values.global.aws_region | quote }}
      {{- if .Values.thanos.kmsKeyArn }}
      sse_config:
        type: "SSE-KMS"
        kms_key_id: {{ .Values.thanos.kmsKeyArn | quote }}
      {{- end }}
{{- end }}
