apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "thanos-operator.namespace" . }}
  labels:
    {{- include "thanos-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "thanos-operator.annotations" . | nindent 4 }}
    {{- if .Values.global.aws_account_id }}
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s-thanos" .Values.global.aws_account_id .Values.global.cluster_name | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
