apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.hyperfleetSentinelChart.applicationName }}
  namespace: {{ .Values.hyperfleetSentinelChart.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.hyperfleetSentinelChart.project }}

  source:
    repoURL: {{ .Values.hyperfleetSentinelChart.source.repoURL }}
    targetRevision: {{ .Values.hyperfleetSentinelChart.source.targetRevision }}
    path: {{ .Values.hyperfleetSentinelChart.source.path }}
    {{- if .Values.hyperfleetSentinelChart.values }}
    helm:
      valuesObject:
        {{- toYaml .Values.hyperfleetSentinelChart.values | nindent 8 }}
    {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.hyperfleetSentinelChart.targetNamespace }}

  syncPolicy:
    {{- if .Values.hyperfleetSentinelChart.syncPolicy.automated }}
    automated:
      prune: {{ .Values.hyperfleetSentinelChart.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.hyperfleetSentinelChart.syncPolicy.automated.selfHeal }}
    {{- end }}
    {{- if .Values.hyperfleetSentinelChart.syncPolicy.syncOptions }}
    syncOptions:
      {{- toYaml .Values.hyperfleetSentinelChart.syncPolicy.syncOptions | nindent 6 }}
    {{- end }}
