version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - |
        chmod +x \
          ./scripts/buildspec/verify-rhobs.sh \
          ./scripts/verify-rhobs-wrapper.sh \
          ./scripts/pipeline-common/init-terraform-backend.sh

  build:
    on-failure: ABORT
    commands:
      - ./scripts/buildspec/verify-rhobs.sh

  post_build:
    commands:
      - echo "RHOBS verification complete."

artifacts:
  files: []
