{{- if .Values.objectStore.config.bucket }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStore.secretName }}
  namespace: {{ include "thanos-operator.namespace" . }}
  labels:
    {{- include "thanos-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "thanos-operator.annotations" . | nindent 4 }}
type: Opaque
stringData:
  objstore.yml: |
    type: {{ .Values.objectStore.config.type }}
    config:
      bucket: {{ .Values.objectStore.config.bucket | quote }}
      endpoint: {{ .Values.objectStore.config.endpoint | quote }}
      region: {{ .Values.objectStore.config.region | quote }}
      {{- if and .Values.objectStore.config.sse_config .Values.objectStore.config.sse_config.kms_key_id }}
      sse_config:
        type: {{ .Values.objectStore.config.sse_config.type | quote }}
        kms_key_id: {{ .Values.objectStore.config.sse_config.kms_key_id | quote }}
      {{- end }}
{{- end }}
