global:
  cluster_name: <cluster-name>
  region: us-east-1
  apiserver_endpoint: https://6739D307E3404938CA4B8CD7C5E79E61.gr7.us-east-1.eks.amazonaws.com
  cluster_ca: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZDJ3a0FvNlIxdzh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMk1UQXhPVEkwTXpWYUZ3MHpOakEyTURjeE9USTVNelZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM0b01lSHZrTVh6U05Wc0JuTTByVlg4V2NpRm1pZGMyZXc2WDBGemR1UnVISnpIZWtLcXlTMUNhbVUKZE1EZjdOV0U2QWdYMUlvVGNKQ2toR3l1aVdsVTNVWHN4NVE5bGVna0dZWWd2V0VJMjMxWTlPdEpBZE5tNzZPRApPQ01rZUF4TTRFUHZ5NkJaQjIxWDFBQUx0a2RRekpRT21NWUt1RjhLTHFoQUZ2VVkyZGU4ejdZSis0RXZ2eW1KCmwvMk5tM3NEdFdjTkE4M25vdlRDN1lZUGIwYzMvRHdCZkVpQVBRT3A4WTh6akxiRTYzYm8rU2pXOHhCWEhteHIKTWt5bUViNVYzQmhzcmhHUVIxbVZqL1lYTk44M2ErZFVjNlM4MmxaQ3IvSGVwQkRCVWR5WWhjSS9kbDNRVEE4RwpCYVJHUlVuUGVOQzJHeU9hcmNFblZodktaZU83QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTb3c1MktMNFVDeFhiaS81a1cxMXlURUg3N1REQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQklvZEU1VEYrdgozcG10a3UzN0xDY2IxWStiZjF4QWJjMmU0WENvZGRoQVV3enJXVjVHaENpV3Q2OFhhQWV1UVZGMTZyZzZwYlY5CmNtbEg2OHdLZEpaSlA1TFZYbFZtMzRUK0ptaUIxcEVPWU5uMHlqVEIzWlY3aUJTZkRFT1RramVuZ2hmanRQSysKZW5neEE0dEVtSEJ0aExET1ZPSTlhYVdZb1JKYlZ0YjYyNlpXT0Z3d0MydGhMd1dzSzlubUdacVVPTENTeWh5WQpSK2h6Tk9jL2xoU3ljM015eEgxbjJySG1UNjVpaU83cjlIaDZpdlorUUVrSzFEMkNPaDQ3U212M1BtaEtMSWViCmEzdzBzZXArOG1xNFVoOXNsbEttVFp2TjMwM3JnbnhNQmI4WENnYzFCanhBSE5SdThkbjVBcnRTRS9DNlpndkIKcXZBdE54cElqODBiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  service_cidr: "172.20.0.0/16"

eksNodeClass:
  amiIds:
    - ami-0dbbd77d98c659bb4 # RHEL 9 FIPS K8s 1.34 us-east-1 (built 2026-06-15)
    # Add 1.35 and 1.36 AMI IDs here once built

eksNodePool:
  instanceFamilies:
    - m8i
    - m7i
  capacityType: on-demand
  arch: amd64
  limits:
    cpu: "64"
    memory: 256Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s
