{{- if .Values.rhobsAgent.otelCollector.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rhobsAgent.otelCollector.serviceAccount.name }}
  namespace: {{ .Values.rhobsAgent.namespace }}
  labels:
    {{- include "rhobs-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
{{- end }}

{{- if .Values.rhobsAgent.fluentBit.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rhobsAgent.fluentBit.serviceAccount.name }}
  namespace: {{ .Values.rhobsAgent.namespace }}
  labels:
    {{- include "rhobs-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: fluent-bit
{{- end }}
