aws-load-balancer-controller:
  # clusterName injected via ApplicationSet valuesObject (aws-load-balancer-controller.clusterName)
  serviceAccount:
    create: true
    name: aws-load-balancer-controller

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
