environment:
  domain: int0.rosa.devshift.net

terraform_vars:
  enable_bastion: true
  environment_domain: "{{ environment_config.domain }}"

region_deployments:
  us-east-1:
    management_clusters:
      mc01: {}
