apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rhobs.namespace }}
  labels:
    {{- include "rhobs.labels" . | nindent 4 }}
    environment: {{ .Values.global.environment | quote }}
    aws-region: {{ include "rhobs.awsRegion" . | quote }}
