{{- if .Values.rhobs.thanos.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rhobs.thanos.serviceAccount.name }}
  namespace: {{ .Values.rhobs.namespace }}
  labels:
    {{- include "rhobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: thanos
  {{- if .Values.rhobs.thanos.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.rhobs.thanos.serviceAccount.roleArn | quote }}
  {{- end }}
{{- end }}

{{- if .Values.rhobs.loki.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rhobs.loki.serviceAccount.name }}
  namespace: {{ .Values.rhobs.namespace }}
  labels:
    {{- include "rhobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
  {{- if .Values.rhobs.loki.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.rhobs.loki.serviceAccount.roleArn | quote }}
  {{- end }}
{{- end }}

{{- if .Values.rhobs.grafana.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: {{ .Values.rhobs.namespace }}
  labels:
    {{- include "rhobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}

{{- if .Values.rhobs.alertmanager.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: {{ .Values.rhobs.namespace }}
  labels:
    {{- include "rhobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
{{- end }}
