{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "rhobs-cell.namespace" $ }}
  labels:
    {{- include "rhobs-cell.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
